[package]
name = "wormhole"
version.workspace = true
edition.workspace = true

[dependencies]
# alloy
alloy-primitives.workspace = true
alloy-provider = { workspace = true, features = ["reqwest"] }
alloy-eips.workspace = true
alloy-wormhole = { workspace = true, features = ["serde"] }
wormhole-program-core = { workspace = true, features = ["serde"] }

# sp1
sp1-sdk.workspace = true

# risc0
risc0-zkvm.workspace = true

tokio = { workspace = true, features = ["macros"] }
clap.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
sp1-build.workspace = true
risc0-build.workspace = true

[package.metadata.risc0]
methods = ["../../programs/risc0"]
